spring:

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${OE_DB_URL}
    username: ${OE_DB_USER}
    password: ${OE_DB_PW}

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        globally_quoted_identifiers: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

cloud:
  aws:
    s3:
      bucket: insureprobucket
    credentials:
      access-key: ${OE_S3_ACCESS}
      secret-key: ${OE_S3_SECRET}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    project.backend: debug

jwt:
  secret: ${OE_SECRET}
  kakao:
    client_id: ${OE_KAKAO_CLIENT_ID}




server:
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-alias: OE
    key-store-password: ${OE_SSL_PW}
    enabled: true
  error:
    include-exception: true
    path: '/error'
    whitelabel:
      enabled: true

